baseURL: /
languageCode: en-us
defaultContentLanguage: en
theme: hugo-devresume-theme
title: Andrea Petreti - CV

languages:
  en:
    languageName: "English"
    languageIcon: "assets/gb.png"
    curriculumPdf: "assets/cvs/andreapetreti-en.pdf"
    skills:
      enable: true
      list:
        - title: Technical
          items: &tech-skills
            - details: Computer Vision Skills (OpenCV + Machine Learning CNN)
            - details: Android
            - details: Flutter(Dart)
            - details: Java/Kotlin/Scala
            - details: C/C++
            - details: JavaScript/Vue
            - details: Python/Keras
            - details: Node.js
            - details: DevOps/Gradle/Continous Integration (like Jenkins)
            - details: Functional and Reactive Programming
        - title: Professional
          items:
            - details: Team player
            - details: Good time management
            - details: Proactive Learning
    education:
      enable: true
      list:
        - degree: Master's Degree in Computer Science and Software Engineering
          university: Bologna University (Cesena) \\ 110/110 with honors
          dates: '2021'
        - degree: Bachelor's Degree in Computer Science
          university: Urbino University \\ 108/110
          dates: '2018'
        - degree: Graduation in Computer Science
          university: ITIS E. Mattei Urbino \\ 86/100
          dates: '2015'
    languages:
      enable: true
      list:
        - name: Italian
          level: Native
        - name: English
          level: Professional
    interests:
      enable: true
      list:
        - name: Home automation
        - name: Maker
        - name: Ski
        - name: Travelling
        - name: Technology
    projects:
      enable: true
      list:
        - title: IntelliSerra
          meta: Open Source | University
          tagline: >-
            Framework developed in Scala which allows managing smart greenhouse. It allows defining smart greenhouse through sensors and actuators and supports an event-based actuation rules system. 
            The main technologies used in this project are Scala, Akka and Prolog, and it developed with Marta Luffarelli, Simone Letizi and Ylenia Battistini.
        - title: Scanbage
          meta: Open Source | University
          tagline: >-
            A powerful web app to recognize types of garbage by photo or barcode through convolutional network (CNN Machine Learning).
             It is a kind of social based on rewards unlocked through the correct differentiation of garbage. 
             The project has been realized in a university context with Gianluca Aguzzi, Marta Luffarelli and Simone Letizi.
        - title: Fluvium
          meta: Open Source | University
          tagline: >-
            A full stack system for monitoring river rise levels. The system has been developed starting from embedded components (ESP32) up to the web/cloud layer based on AWS. 
            The project is realized in university context with Gianluca Aguzzi.
        - title: Face Sketch Recognition - CBIR
          meta: Computer Vision  | University
          tagline: >-
            University project aimed at finding faces based on the similarity of sketches obtained manually or through identikit software.
        - title: Home Assistant Tapo P100 Integration
          meta: Open Source | Home Automation
          tagline: >-
            Integration for controlling smart plugs and smart lights of the [Tapo](https://www.tapo.com/en/) line through 
            the well-known home automation assistant [Home Assistant](https://www.home-assistant.io/). 
            Made mainly in Python, this is the main integration used in the Home Assistant community. 
        - title: Subspedia
          meta: Android App
          tagline: >-
            Mobile application for the subtitling website Subspedia (now discontinued).
    summary:
      enable: true
      text: >-
        I got my bachelor degree in Applied Informatics at Urbino University; later I decided to deepen my studies with a master degree in studies with a 
        master degree in Engineering and Computer Science at the University of Bologna (at Cesena). 
        During this last path I decided to focus on the world of software engineering; I love the quality of the code. 
        The course of study also allowed me to acquire skills related to Computer Vision both through traditional techniques and through machine learning. 
        I'm particularly passionate about the world related to IoT, robotics and artificial intelligence. I enjoy any challenge related to the IT world. 
    experience:
      enable: true
      list:
        #- title: Corso Android
        #  dates: 6 mesi 2018 - 2018
        #  company: Green Dreams (Startup)
        #  details: >-
        #    Sviluppatore full stack per dispositivi embedded legati all'industria
        #    4.0. Tecnologie basate principalmente su C#/Java/C++.
        - title: Android and Flutter Developer
          dates: May 2021 - now
          company: Sysdata s.p.a
          details: |
            Android and Flutter developer. Main projects and technologies:
            - Luxottica - Leonardo (Android - Kotlin)
            - AllianzNow App (Android - Java)
            - Japan Tobacco Ambassador App (Flutter)
            - Maserati Owner App (Android - Kotlin)
            - MyCRA App (Android - Java)
            - Snam (Android - Kotlin)
        - title: Full Stack Developer
          dates: 6 month 2018 - 2018
          company: Green Dreams (Startup)
          details: >-
            Full stack developer for industry related embedded devices 4.0. 
            Technologies based mainly on C#/Java/C++. 
            Management of small projects in collaboration with [Loccioni](http://loccioni.com)
    
  it:
    languageName: "Italiano"
    languageIcon: "assets/it.png"
    curriculumPdf: "assets/cvs/andreapetreti-it.pdf"
    skills:
      enable: true
      list:
        - title: Technical
          items: *tech-skills
        - title: Professional
          items:
            - details: Team player
            - details: Buona gestione del tempo
            - details: Proattivo
    education:
      enable: true
      list:
        - degree: Laurea in Ingegneria e Scienze Informatiche
          university: Università di Bologna (Campus Cesena) \\ 110/110 e lode
          dates: '2021'
        - degree: Laurea Informatica Applicata
          university: Università degli Studi di Urbino Carlo Bo \\ 108/110
          dates: '2018'
        - degree: Diploma in Informatica
          university: ITIS E. Mattei Urbino \\ 86/100
          dates: '2015'
    languages:
      enable: true
      list:
        - name: Italiano
          level: Madre lingua
        - name: English
          level: Professionale
    interests:
      enable: true
      list:
        - name: Home automation
        - name: Maker
        - name: Scii
        - name: Viaggiare
        - name: Tecnologia
    projects:
      enable: true
      list:
        - title: IntelliSerra
          meta: Open Source | Università
          tagline: >-
            Framework per la gestione di serre intelligenti sviluppato in Scala. Il framwork consente di definire serre intelligenti attraverso sensori/attuatori e di poter definire
            regole di automazione basate su eventi. Le tecnologie utilizzate sono prevalentemente Scala, Akka e Prolog. Sviluppato in collaborazione con Marta Luffarelli e Simone Letizi e Ylenia Battistini.
        - title: Scanbage
          meta: Open Source | Università
          tagline: >-
            Una potente web app per riconoscere i tipi di spazzatura tramite foto o codice a barre tramite rete convuluzionale (CNN Machine Learning).
            Si tratta di una sorta di social basati su premi sbloccati attraverso la corretta differenziazione dei rifiuti.
            Il progetto è stato realizzato in contesto universitario con Gianluca Aguzzi, Marta Luffarelli e Simone Letizi.
        - title: Fluvium
          meta: Open Source | Università
          tagline: >-
            Un sistema full stack per il monitoraggio del livello di innalzamento dei fiumi. Il sistema è stato sviluppato partendo da componenti embedded (ESP32) fino al livello web/cloud basato su AWS.
            Il progetto è realizzato in contesto universitario con Gianluca Aguzzi.
        - title: Face Sketch Recognition - CBIR
          meta: Computer Vision  | Università
          tagline: >-
            Progetto universitario volto alla ricerca di volti in base alla similirità di sketch ottenuti manualmente o tramite software di identikit.
        - title: Home Assistant Tapo P100 Integration
          meta: Open Source | Home Automation
          tagline: >-
            Integrazione per il controllo di smart plug e luci intelligenti della linea [Tapo](https://www.tapo.com/en/) tramite il noto assistente domotico [Home Assistant](https://www.home-assistant.io/). 
            Realizzata principlamente in Python, si tratta della principale integrazione utilizzata nella comunita di Home Assistant. 
        - title: Subspedia
          meta: App Android
          tagline: >-
            Applicazione mobile per il sito web di sottotitoli Subspedia (ormai dismesso).
    summary:
      enable: true
      text: >-
        Ho conseguito la laurea triennale in Informatica Applicata presso Urbino; in seguito ho deciso di approfondire i miei 
        studi con una laurea magistrale in Ingegneria e Scienze Informatiche presso l'Università di Bologna (sede Cesena).
        Durante quest'ultimo percorso ho deciso di focalizzarmi verso il mondo dell'ingegneria del software; amo la qualità del codice.
        Il percorso di studi, inoltre, mi ha consentito di acquisire abilità relative alla Computer Vision sia mediante tecniche tradizionali sia tramite machine learning.
        Sono particolarmente appassionato al mondo relativo all'IoT, alla robotica e all'intelligenza artificiale. In generale mi diverto con ogni sfida relativa al mondo dell'IT. 
    experience:
      enable: true
      list:
        #- title: Corso Android
        #  dates: 6 mesi 2018 - 2018
        #  company: Green Dreams (Startup)
        #  details: >-
        #    Sviluppatore full stack per dispositivi embedded legati all'industria
        #    4.0. Tecnologie basate principalmente su C#/Java/C++.
        - title: Android and Flutter Developer
          dates: Maggio 2021 - adesso
          company: Sysdata s.p.a
          details: |
            Android e Flutter developer. Principali progetti e relative tecnologie:
            - Luxottica - Leonardo (Android - Kotlin)
            - AllianzNow App (Android - Java)
            - Japan Tobacco Ambassador App (Flutter)
            - Maserati Owner App (Android - Kotlin)
            - MyCRA App (Android - Java)
            - Snam (Android - Kotlin)
        - title: Full Stack Developer
          dates: 6 mesi 2018 - 2018
          company: Green Dreams (Startup)
          details: >-
            Sviluppatore full stack per dispositivi embedded legati all'industria
            4.0. Tecnologie basate principalmente su C#/Java/C++. Gestione di
            progetti di piccole dimensioni in collaborazione con
            [Loccioni](http://loccioni.com)

params:
  author: CowboySmall
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  primaryColor: '#54B689'
  textPrimaryColor: '#292929'
  profile:
    enable: true
    name: Andrea Petreti
    #agline: 'TODO: add role e.g. Software Dev or Engineer or other'
    avatar: my-avatar-round.png
  contact:
    enable: true
    location: Italy
    list:
      - icon: fas fa-phone-square
        url: 'tel:#+393348782198'
        text: +39 334 8782198
      - icon: fas fa-envelope-square
        url: 'mailto:#petretiandrea@gmail.com'
        text: petretiandrea@gmail.com
      - icon: fas fa-globe
        url: 'http://petretiandrea.github.io'
        text: petretiandrea.github.io
  awards:
    enable: false
    list:
      - name: Award Lorem Ipsum
        body: Microsoft lorem ipsum
        date: '2019'
      - name: Award Donec Sodales
        body: Oracle Aenean
        date: '2017'
  publications:
    enable: true
    list:
      - title: Encouraging users in waste sorting using deep neural networks and gamification
        company: Association of Computer Machinery
        dates: Sep 2021
        details: >- 
          This paper presents ScanBage, a web application designed and developed to support users in separating waste collection. 
          It exploits two machine learning algorithms to automatically classify garbage categories 
          and it employs Gamification elements with the aim of increasing user involvement.
          [https://dl.acm.org/doi/abs/10.1145/3462203.3477056](https://dl.acm.org/doi/abs/10.1145/3462203.3477056)
  social:
    enable: true
    list:
      - icon: fab fa-github-square
        url: //github.com/petretiandrea
        title: GitHub
      - icon: fab fa-linkedin
        url: //linkedin.com/in/andrea-petreti
        title: LinkedIn